parameters:
    grocerylist.app_services.list.class: GroceryList\APIBundle\Common\ApplicationServices\ListAppService

services:
   grocerylist.app_services.list:
       class: %grocerylist.app_services.list.class%

